-- phpMyAdmin SQL Dump
-- version 4.1.14
-- http://www.phpmyadmin.net
--
-- Client :  127.0.0.1
-- Généré le :  Mar 11 Juillet 2017 à 09:32
-- Version du serveur :  5.6.17
-- Version de PHP :  5.5.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Base de données :  `hair`
--
CREATE DATABASE IF NOT EXISTS `hair` DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci;
USE `hair`;

-- --------------------------------------------------------

--
-- Structure de la table `blog`
--

DROP TABLE IF EXISTS `blog`;
CREATE TABLE IF NOT EXISTS `blog` (
  `id` int(10) NOT NULL AUTO_INCREMENT,
  `couverture` varchar(255) NOT NULL,
  `content` text NOT NULL,
  `date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `titre` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=102 ;

--
-- Contenu de la table `blog`
--

INSERT INTO `blog` (`id`, `couverture`, `content`, `date`, `titre`) VALUES
(2, '/media/Articles/38343230.jpg', '<p>In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.</p>\r\n', '2017-07-08 22:52:25', 'Salute'),
(3, '/media/Articles/3132393936.jpg', '<p>Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis. Sed ante. Vivamus tortor. Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.</p>\r\n', '2017-07-08 22:52:25', 'felis sed'),
(4, '/media/Articles/3131363033.png', '<p>Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.</p>\r\n', '2017-07-08 22:52:25', 'fdsfsdfsdf sdf sdf'),
(5, '/media/testcarousel.jpg', 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.\r\n\r\nInteger ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.\r\n\r\nNam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.\r\n\r\nCurabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', '2017-07-08 22:52:25', 'nulla integer pede justo'),
(6, '/media/testcarousel.jpg', 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.\r\n\r\nMaecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.\r\n\r\nNullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.', '2017-07-08 22:52:25', 'sapien in sapien iaculis congue vivamus metus'),
(7, '/media/test_carousel2.jpg', 'Phasellus in felis. Donec semper sapien a libero. Nam dui.\r\n\r\nProin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.\r\n\r\nInteger ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.\r\n\r\nNam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.\r\n\r\nCurabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', '2017-07-08 22:52:25', 'maecenas rhoncus aliquam lacus morbi quis tortor'),
(8, '/media/test_carousel2.jpg', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.\r\n\r\nEtiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.\r\n\r\nPraesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.', '2017-07-08 22:52:25', 'ut ultrices vel augue vestibulum'),
(9, '/media/testcarousel.jpg', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.\r\n\r\nDuis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.\r\n\r\nMauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.\r\n\r\nNullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.', '2017-07-08 22:52:25', 'sapien quis libero nullam sit'),
(10, '/media/testcarousel.jpg', 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.\r\n\r\nAliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.\r\n\r\nSed ante. Vivamus tortor. Duis mattis egestas metus.\r\n\r\nAenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', '2017-07-08 22:52:25', 'volutpat convallis morbi odio odio'),
(11, '/media/test_carousel2.jpg', 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.\r\n\r\nPhasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.\r\n\r\nProin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', '2017-07-08 22:52:25', 'arcu adipiscing molestie hendrerit at'),
(12, '/media/test_carousel2.jpg', 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.\r\n\r\nNulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.\r\n\r\nCras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.\r\n\r\nQuisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', '2017-07-08 22:52:25', 'nec molestie sed justo pellentesque'),
(13, '/media/testcarousel.jpg', 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.\r\n\r\nMorbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.\r\n\r\nFusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.', '2017-07-08 22:52:25', 'est congue elementum in hac habitasse platea'),
(14, '/media/test_carousel2.jpg', 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.\r\n\r\nIn hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.\r\n\r\nAliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.\r\n\r\nSed ante. Vivamus tortor. Duis mattis egestas metus.', '2017-07-08 22:52:25', 'vehicula condimentum curabitur in'),
(15, '/media/test_carousel2.jpg', 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.\r\n\r\nPellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.\r\n\r\nCum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', '2017-07-08 22:52:25', 'rhoncus aliquet pulvinar sed'),
(16, '/media/testcarousel.jpg', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.\r\n\r\nNullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.\r\n\r\nMorbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', '2017-07-08 22:52:25', 'nulla suscipit ligula'),
(17, '/media/testcarousel.jpg', 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.\r\n\r\nMauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.\r\n\r\nNullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.\r\n\r\nIn quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.\r\n\r\nMaecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.', '2017-07-08 22:52:25', 'ultrices erat tortor sollicitudin mi sit'),
(18, '/media/testcarousel.jpg', 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.\r\n\r\nCurabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.\r\n\r\nInteger tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', '2017-07-08 22:52:26', 'commodo vulputate justo'),
(19, '/media/testcarousel.jpg', 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.\r\n\r\nSed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.\r\n\r\nPellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.\r\n\r\nCum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.\r\n\r\nEtiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', '2017-07-08 22:52:26', 'luctus et ultrices'),
(20, '/media/testcarousel.jpg', 'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.\r\n\r\nSuspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.\r\n\r\nMaecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.', '2017-07-08 22:52:26', 'orci luctus et ultrices'),
(21, '/media/test_carousel2.jpg', 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.\r\n\r\nVestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.\r\n\r\nIn congue. Etiam justo. Etiam pretium iaculis justo.\r\n\r\nIn hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.\r\n\r\nNulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.', '2017-07-08 22:52:26', 'adipiscing elit proin risus'),
(22, '/media/test_carousel2.jpg', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.\r\n\r\nNullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.\r\n\r\nIn quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.', '2017-07-08 22:52:26', 'vestibulum rutrum rutrum neque aenean auctor'),
(23, '/media/test_carousel2.jpg', 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.\r\n\r\nIn quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.\r\n\r\nMaecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.', '2017-07-08 22:52:26', 'condimentum curabitur in libero ut massa'),
(24, '/media/testcarousel.jpg', 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.\r\n\r\nFusce consequat. Nulla nisl. Nunc nisl.\r\n\r\nDuis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.\r\n\r\nIn hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', '2017-07-08 22:52:26', 'velit vivamus vel nulla eget eros elementum'),
(25, '/media/test_carousel2.jpg', 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.\r\n\r\nFusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.\r\n\r\nSed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.\r\n\r\nPellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.\r\n\r\nCum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', '2017-07-08 22:52:26', 'pharetra magna vestibulum aliquet ultrices'),
(26, '/media/testcarousel.jpg', 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.\r\n\r\nMorbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.\r\n\r\nFusce consequat. Nulla nisl. Nunc nisl.\r\n\r\nDuis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.\r\n\r\nIn hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', '2017-07-08 22:52:26', 'nam dui'),
(27, '/media/testcarousel.jpg', 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.\r\n\r\nPraesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.\r\n\r\nMorbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.\r\n\r\nFusce consequat. Nulla nisl. Nunc nisl.\r\n\r\nDuis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.', '2017-07-08 22:52:26', 'ut blandit non interdum in ante vestibulum'),
(28, '/media/test_carousel2.jpg', 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.\r\n\r\nPellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.\r\n\r\nCum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', '2017-07-08 22:52:26', 'orci mauris lacinia sapien quis libero nullam'),
(29, '/media/testcarousel.jpg', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.\r\n\r\nNullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.\r\n\r\nIn quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.\r\n\r\nMaecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.\r\n\r\nMaecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.', '2017-07-08 22:52:26', 'leo odio porttitor id'),
(30, '/media/testcarousel.jpg', 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.\r\n\r\nPellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.\r\n\r\nCum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', '2017-07-08 22:52:26', 'vestibulum vestibulum ante ipsum primis'),
(31, '/media/testcarousel.jpg', 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.\r\n\r\nFusce consequat. Nulla nisl. Nunc nisl.\r\n\r\nDuis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.\r\n\r\nIn hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.\r\n\r\nAliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.', '2017-07-08 22:52:26', 'integer a nibh in'),
(32, '/media/test_carousel2.jpg', 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.\r\n\r\nSed ante. Vivamus tortor. Duis mattis egestas metus.\r\n\r\nAenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.\r\n\r\nQuisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.\r\n\r\nVestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', '2017-07-08 22:52:26', 'aliquam convallis nunc proin at'),
(33, '/media/testcarousel.jpg', 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.\r\n\r\nCum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.\r\n\r\nEtiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', '2017-07-08 22:52:26', 'elit ac nulla sed vel'),
(34, '/media/test_carousel2.jpg', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.\r\n\r\nNullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.\r\n\r\nIn quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.\r\n\r\nMaecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.', '2017-07-08 22:52:26', 'neque sapien'),
(35, '/media/testcarousel.jpg', 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.\r\n\r\nQuisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.\r\n\r\nVestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.\r\n\r\nIn congue. Etiam justo. Etiam pretium iaculis justo.', '2017-07-08 22:52:26', 'potenti in eleifend'),
(36, '/media/testcarousel.jpg', 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.\r\n\r\nPraesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.\r\n\r\nCras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.\r\n\r\nProin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', '2017-07-08 22:52:26', 'ultrices libero non'),
(37, '/media/testcarousel.jpg', 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.\r\n\r\nMauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.\r\n\r\nNullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.', '2017-07-08 22:52:26', 'nisl duis ac nibh'),
(38, '/media/test_carousel2.jpg', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.\r\n\r\nVestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.\r\n\r\nDuis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.\r\n\r\nMauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.', '2017-07-08 22:52:26', 'nisi at'),
(39, '/media/testcarousel.jpg', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.\r\n\r\nNullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.\r\n\r\nMorbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.\r\n\r\nFusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.\r\n\r\nSed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', '2017-07-08 22:52:26', 'odio justo sollicitudin'),
(40, '/media/test_carousel2.jpg', 'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.\r\n\r\nProin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.\r\n\r\nDuis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.\r\n\r\nDonec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.\r\n\r\nDuis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.', '2017-07-08 22:52:26', 'nisl ut volutpat sapien arcu sed'),
(41, '/media/testcarousel.jpg', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.\r\n\r\nNullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.\r\n\r\nMorbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.\r\n\r\nFusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.\r\n\r\nSed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', '2017-07-08 22:52:26', 'tortor sollicitudin mi sit'),
(42, '/media/test_carousel2.jpg', 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.\r\n\r\nIn quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.\r\n\r\nMaecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.\r\n\r\nMaecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.\r\n\r\nNullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.', '2017-07-08 22:52:26', 'montes nascetur ridiculus mus etiam vel augue'),
(43, '/media/testcarousel.jpg', 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.\r\n\r\nQuisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.\r\n\r\nVestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.\r\n\r\nIn congue. Etiam justo. Etiam pretium iaculis justo.\r\n\r\nIn hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.', '2017-07-08 22:52:26', 'non lectus aliquam sit amet'),
(44, '/media/test_carousel2.jpg', 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.\r\n\r\nMaecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.\r\n\r\nNullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.\r\n\r\nMorbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', '2017-07-08 22:52:26', 'sed interdum venenatis turpis enim blandit'),
(45, '/media/test_carousel2.jpg', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.\r\n\r\nNullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.\r\n\r\nMorbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.\r\n\r\nFusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.\r\n\r\nSed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', '2017-07-08 22:52:26', 'mus vivamus vestibulum sagittis sapien'),
(46, '/media/testcarousel.jpg', 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.\r\n\r\nFusce consequat. Nulla nisl. Nunc nisl.\r\n\r\nDuis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.\r\n\r\nIn hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.\r\n\r\nAliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.', '2017-07-08 22:52:26', 'justo etiam pretium iaculis'),
(47, '/media/test_carousel2.jpg', 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.\r\n\r\nCras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.\r\n\r\nProin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', '2017-07-08 22:52:26', 'cras in purus'),
(48, '/media/testcarousel.jpg', 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.\r\n\r\nCurabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.\r\n\r\nInteger tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.\r\n\r\nPraesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', '2017-07-08 22:52:26', 'ultrices aliquet'),
(49, '/media/test_carousel2.jpg', 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.\r\n\r\nCurabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.\r\n\r\nPhasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.\r\n\r\nProin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.\r\n\r\nDuis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.', '2017-07-08 22:52:26', 'vestibulum proin eu mi nulla ac'),
(50, '/media/testcarousel.jpg', 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.\r\n\r\nPhasellus in felis. Donec semper sapien a libero. Nam dui.\r\n\r\nProin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.\r\n\r\nInteger ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.\r\n\r\nNam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', '2017-07-08 22:52:26', 'eu sapien cursus vestibulum proin'),
(51, '/media/testcarousel.jpg', 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.\r\n\r\nIn congue. Etiam justo. Etiam pretium iaculis justo.\r\n\r\nIn hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.\r\n\r\nNulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.', '2017-07-08 22:52:26', 'tristique in tempus sit amet sem fusce'),
(52, '/media/testcarousel.jpg', 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.\r\n\r\nInteger tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.\r\n\r\nPraesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.\r\n\r\nMorbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', '2017-07-08 22:52:26', 'laoreet ut rhoncus aliquet pulvinar sed'),
(53, '/media/test_carousel2.jpg', 'Sed ante. Vivamus tortor. Duis mattis egestas metus.\r\n\r\nAenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.\r\n\r\nQuisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', '2017-07-08 22:52:27', 'dapibus augue vel'),
(54, '/media/test_carousel2.jpg', 'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.\r\n\r\nNam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.\r\n\r\nCurabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', '2017-07-08 22:52:27', 'mauris non ligula pellentesque ultrices phasellus id'),
(55, '/media/test_carousel2.jpg', 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.\r\n\r\nNulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.\r\n\r\nCras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', '2017-07-08 22:52:27', 'aenean auctor gravida sem praesent'),
(56, '/media/testcarousel.jpg', 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.\r\n\r\nMorbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.\r\n\r\nFusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.', '2017-07-08 22:52:27', 'pede justo'),
(57, '/media/test_carousel2.jpg', 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.\r\n\r\nDuis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.\r\n\r\nIn sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.\r\n\r\nSuspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.\r\n\r\nMaecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.', '2017-07-08 22:52:27', 'ut tellus nulla ut erat'),
(58, '/media/testcarousel.jpg', 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.\r\n\r\nAliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.\r\n\r\nSed ante. Vivamus tortor. Duis mattis egestas metus.\r\n\r\nAenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.\r\n\r\nQuisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', '2017-07-08 22:52:27', 'in hac habitasse platea dictumst'),
(59, '/media/test_carousel2.jpg', 'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.\r\n\r\nSuspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.\r\n\r\nMaecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.\r\n\r\nCurabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', '2017-07-08 22:52:27', 'nam tristique tortor'),
(60, '/media/testcarousel.jpg', 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.\r\n\r\nAliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.\r\n\r\nSed ante. Vivamus tortor. Duis mattis egestas metus.\r\n\r\nAenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.\r\n\r\nQuisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', '2017-07-08 22:52:27', 'lorem ipsum dolor sit amet consectetuer adipiscing'),
(61, '/media/test_carousel2.jpg', 'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.\r\n\r\nCras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.\r\n\r\nQuisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.\r\n\r\nPhasellus in felis. Donec semper sapien a libero. Nam dui.', '2017-07-08 22:52:27', 'eleifend donec ut dolor morbi vel'),
(62, '/media/test_carousel2.jpg', 'In congue. Etiam justo. Etiam pretium iaculis justo.\r\n\r\nIn hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.\r\n\r\nNulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.\r\n\r\nCras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.\r\n\r\nQuisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', '2017-07-08 22:52:27', 'lectus pellentesque at'),
(63, '/media/test_carousel2.jpg', 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.\r\n\r\nCum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.\r\n\r\nEtiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.\r\n\r\nPraesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.\r\n\r\nCras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', '2017-07-08 22:52:27', 'quam fringilla'),
(64, '/media/test_carousel2.jpg', 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.\r\n\r\nNulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.\r\n\r\nCras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.\r\n\r\nQuisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', '2017-07-08 22:52:27', 'id turpis integer aliquet'),
(65, '/media/testcarousel.jpg', 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.\r\n\r\nFusce consequat. Nulla nisl. Nunc nisl.\r\n\r\nDuis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.\r\n\r\nIn hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.\r\n\r\nAliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.', '2017-07-08 22:52:27', 'dis parturient montes nascetur'),
(66, '/media/test_carousel2.jpg', 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.\r\n\r\nAenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.\r\n\r\nCurabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.\r\n\r\nPhasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.\r\n\r\nProin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', '2017-07-08 22:52:27', 'quam sapien varius'),
(67, '/media/testcarousel.jpg', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.\r\n\r\nNullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.\r\n\r\nIn quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.', '2017-07-08 22:52:27', 'nonummy integer non velit donec diam neque'),
(68, '/media/testcarousel.jpg', 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.\r\n\r\nDuis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.\r\n\r\nDonec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.\r\n\r\nDuis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.', '2017-07-08 22:52:27', 'vel augue vestibulum rutrum rutrum'),
(69, '/media/test_carousel2.jpg', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.\r\n\r\nNullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.\r\n\r\nMorbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.\r\n\r\nFusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.\r\n\r\nSed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', '2017-07-08 22:52:27', 'vel enim sit amet nunc'),
(70, '/media/testcarousel.jpg', 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.\r\n\r\nMorbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.\r\n\r\nFusce consequat. Nulla nisl. Nunc nisl.\r\n\r\nDuis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.\r\n\r\nIn hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', '2017-07-08 22:52:27', 'ultrices vel augue vestibulum ante'),
(71, '/media/testcarousel.jpg', 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.\r\n\r\nPhasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.\r\n\r\nProin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', '2017-07-08 22:52:27', 'id nulla ultrices aliquet maecenas leo odio'),
(72, '/media/testcarousel.jpg', 'Fusce consequat. Nulla nisl. Nunc nisl.\r\n\r\nDuis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.\r\n\r\nIn hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', '2017-07-08 22:52:27', 'congue eget semper rutrum nulla'),
(73, '/media/testcarousel.jpg', 'In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.\r\n\r\nMaecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.\r\n\r\nMaecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.', '2017-07-08 22:52:27', 'semper porta volutpat quam pede'),
(74, '/media/testcarousel.jpg', 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.\r\n\r\nSed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.\r\n\r\nPellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.', '2017-07-08 22:52:27', 'nec dui luctus rutrum nulla tellus'),
(75, '/media/testcarousel.jpg', 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.\r\n\r\nDonec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.\r\n\r\nDuis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.', '2017-07-08 22:52:27', 'eget eleifend'),
(76, '/media/testcarousel.jpg', 'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.\r\n\r\nNam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.\r\n\r\nCurabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', '2017-07-08 22:52:27', 'natoque penatibus'),
(77, '/media/testcarousel.jpg', 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.\r\n\r\nCurabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.\r\n\r\nPhasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.\r\n\r\nProin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', '2017-07-08 22:52:27', 'non sodales sed tincidunt eu felis'),
(78, '/media/testcarousel.jpg', 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.\r\n\r\nPhasellus in felis. Donec semper sapien a libero. Nam dui.\r\n\r\nProin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.', '2017-07-08 22:52:27', 'turpis adipiscing lorem vitae'),
(79, '/media/testcarousel.jpg', 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.\r\n\r\nPraesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.\r\n\r\nMorbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', '2017-07-08 22:52:27', 'at velit vivamus vel nulla eget'),
(80, '/media/testcarousel.jpg', 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.\r\n\r\nSed ante. Vivamus tortor. Duis mattis egestas metus.\r\n\r\nAenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.\r\n\r\nQuisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.\r\n\r\nVestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', '2017-07-08 22:52:27', 'nam ultrices libero non'),
(81, '/media/test_carousel2.jpg', 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.\r\n\r\nNulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.\r\n\r\nCras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', '2017-07-08 22:52:27', 'primis in'),
(82, '/media/test_carousel2.jpg', 'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.\r\n\r\nNam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.\r\n\r\nCurabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', '2017-07-08 22:52:27', 'eget eros elementum pellentesque');
INSERT INTO `blog` (`id`, `couverture`, `content`, `date`, `titre`) VALUES
(83, '/media/testcarousel.jpg', 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.\r\n\r\nCurabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.\r\n\r\nInteger tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.\r\n\r\nPraesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', '2017-07-08 22:52:28', 'diam neque vestibulum eget'),
(84, '/media/testcarousel.jpg', 'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.\r\n\r\nCras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.\r\n\r\nQuisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.\r\n\r\nPhasellus in felis. Donec semper sapien a libero. Nam dui.', '2017-07-08 22:52:28', 'semper interdum mauris ullamcorper purus sit amet'),
(85, '/media/test_carousel2.jpg', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.\r\n\r\nNullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.\r\n\r\nMorbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.\r\n\r\nFusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.', '2017-07-08 22:52:28', 'blandit lacinia'),
(86, '/media/test_carousel2.jpg', 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.\r\n\r\nInteger tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.\r\n\r\nPraesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', '2017-07-08 22:52:28', 'nunc purus phasellus in felis'),
(87, '/media/test_carousel2.jpg', 'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.\r\n\r\nSuspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.\r\n\r\nMaecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.', '2017-07-08 22:52:28', 'est risus auctor sed tristique in'),
(88, '/media/testcarousel.jpg', 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.\r\n\r\nIn congue. Etiam justo. Etiam pretium iaculis justo.\r\n\r\nIn hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.', '2017-07-08 22:52:28', 'ligula nec sem duis aliquam convallis nunc'),
(89, '/media/test_carousel2.jpg', 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.\r\n\r\nDuis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.\r\n\r\nIn sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.\r\n\r\nSuspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.', '2017-07-08 22:52:28', 'ante ipsum primis in'),
(90, '/media/test_carousel2.jpg', 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.\r\n\r\nCras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.\r\n\r\nProin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', '2017-07-08 22:52:28', 'ut suscipit a feugiat et eros'),
(91, '/media/test_carousel2.jpg', 'Phasellus in felis. Donec semper sapien a libero. Nam dui.\r\n\r\nProin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.\r\n\r\nInteger ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.\r\n\r\nNam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', '2017-07-08 22:52:28', 'dolor quis odio consequat'),
(92, '/media/test_carousel2.jpg', 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.\r\n\r\nQuisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.\r\n\r\nVestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.\r\n\r\nIn congue. Etiam justo. Etiam pretium iaculis justo.', '2017-07-08 22:52:28', 'libero nam dui proin leo'),
(93, '/media/test_carousel2.jpg', 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.\r\n\r\nAenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.\r\n\r\nCurabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.\r\n\r\nPhasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', '2017-07-08 22:52:28', 'augue luctus tincidunt nulla mollis'),
(94, '/media/testcarousel.jpg', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.\r\n\r\nDuis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.\r\n\r\nMauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.\r\n\r\nNullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.', '2017-07-08 22:52:28', 'aliquam augue quam sollicitudin vitae consectetuer eget'),
(95, '/media/testcarousel.jpg', 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.\r\n\r\nPhasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.\r\n\r\nProin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', '2017-07-08 22:52:28', 'mi in'),
(96, '/media/test_carousel2.jpg', 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.\r\n\r\nDonec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.\r\n\r\nDuis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.\r\n\r\nIn sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', '2017-07-08 22:52:28', 'non mauris morbi non lectus aliquam sit'),
(97, '/media/test_carousel2.jpg', 'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.\r\n\r\nCras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.\r\n\r\nQuisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.\r\n\r\nPhasellus in felis. Donec semper sapien a libero. Nam dui.', '2017-07-08 22:52:28', 'curabitur in libero ut massa volutpat'),
(98, '/media/test_carousel2.jpg', 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.\r\n\r\nDuis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.\r\n\r\nDonec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.\r\n\r\nDuis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.\r\n\r\nIn sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', '2017-07-08 22:52:28', 'primis in faucibus orci luctus et ultrices'),
(99, '/media/test_carousel2.jpg', 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.\r\n\r\nQuisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.\r\n\r\nPhasellus in felis. Donec semper sapien a libero. Nam dui.\r\n\r\nProin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.', '2017-07-08 22:52:28', 'nulla sed vel enim sit amet'),
(100, '/media/testcarousel.jpg', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.\r\n\r\nVestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.\r\n\r\nDuis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.\r\n\r\nMauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.', '2017-07-08 22:52:28', 'consequat lectus in est risus auctor'),
(101, '/media/Articles/34363834.jpg', '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla sit amet mollis augue. Nulla erat elit, ultrices nec auctor sed, euismod sed erat. Interdum et malesuada fames ac ante ipsum primis in faucibus. Cras sed luctus dui. Pellentesque vitae sem lectus. Mauris molestie imperdiet libero non hendrerit. Sed vitae ipsum odio. Ut vestibulum dolor dolor, sit amet luctus massa euismod ac. Vivamus vitae enim dapibus, placerat ante sit amet, mattis lorem. Nulla eu interdum tortor. Duis eget porta urna, a hendrerit sem. Cras nec aliquam ligula. Sed lacus purus, bibendum id placerat sit amet, congue eget nunc. Cras a metus tortor. Maecenas ut aliquet urna. Maecenas eget purus sit amet nibh tempus malesuada in semper mi.</p>\r\n\r\n<p>Phasellus eu sapien vel orci molestie porta in ac mi. Pellentesque justo elit, consequat nec orci quis, porta tempus lacus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed nec lectus id libero facilisis elementum eget euismod nibh. Pellentesque vitae diam fermentum, efficitur nibh non, lacinia libero. Integer elementum erat dui, sed egestas purus dapibus at. Maecenas iaculis, orci at accumsan fringilla, nisl felis molestie dui, nec mollis erat nulla sed metus. Donec pretium posuere leo, eu luctus nisl facilisis vel. Nam finibus, libero quis hendrerit mollis, ante eros faucibus augue, sed rhoncus augue nisl vehicula eros. Etiam sem ipsum, condimentum luctus velit nec, porta condimentum lorem. Etiam scelerisque nisl justo, malesuada sagittis tellus cursus vel. Praesent posuere suscipit est, quis condimentum erat sagittis non. Curabitur accumsan augue a mi congue elementum. Aliquam erat volutpat.</p>\r\n\r\n<p>Vestibulum eu tempus urna. Sed eget mauris quis purus luctus sagittis ut vel odio. In non lorem efficitur, gravida diam ac, convallis nisl. Vestibulum ultricies ut enim rhoncus eleifend. Vivamus non gravida nibh. Nulla venenatis et odio in vestibulum. Nunc et pharetra ex. Nullam porta placerat odio, eu gravida felis elementum eu.</p>\r\n\r\n<p>Vestibulum facilisis est quis odio viverra, eget vestibulum felis convallis. Vivamus gravida pulvinar purus in lobortis. Nunc tempus elit quis tempus dignissim. Sed euismod pellentesque tortor, et sollicitudin quam efficitur quis. Donec tincidunt pharetra massa sit amet vulputate. Aliquam lectus libero, iaculis at mi a, euismod ultrices mi. Duis mollis metus id tortor fringilla, vitae iaculis justo suscipit. Cras nec lobortis libero. Vivamus imperdiet augue nec laoreet porta. Ut at mi sem. Mauris in tempor nisl, sit amet dignissim ligula.</p>\r\n', '2017-07-09 18:52:35', 'My add  art');

-- --------------------------------------------------------

--
-- Structure de la table `horaire`
--

DROP TABLE IF EXISTS `horaire`;
CREATE TABLE IF NOT EXISTS `horaire` (
  `id` int(10) NOT NULL AUTO_INCREMENT,
  `jour` varchar(100) NOT NULL,
  `matin` varchar(100) NOT NULL,
  `midi` varchar(100) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=3 ;

--
-- Contenu de la table `horaire`
--

INSERT INTO `horaire` (`id`, `jour`, `matin`, `midi`) VALUES
(1, 'Lundi', '10h/11h', '15h/18h'),
(2, 'Mardi', '10h/11h', '15h/18h');

-- --------------------------------------------------------

--
-- Structure de la table `newsletter`
--

DROP TABLE IF EXISTS `newsletter`;
CREATE TABLE IF NOT EXISTS `newsletter` (
  `id` int(10) NOT NULL AUTO_INCREMENT,
  `mail` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=2 ;

--
-- Contenu de la table `newsletter`
--

INSERT INTO `newsletter` (`id`, `mail`) VALUES
(1, 'qsdqsdqs@frefe.gt');

-- --------------------------------------------------------

--
-- Structure de la table `price`
--

DROP TABLE IF EXISTS `price`;
CREATE TABLE IF NOT EXISTS `price` (
  `id` int(10) NOT NULL AUTO_INCREMENT,
  `prix` varchar(3) NOT NULL,
  `content` varchar(255) NOT NULL,
  `to` int(1) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=3 ;

--
-- Contenu de la table `price`
--

INSERT INTO `price` (`id`, `prix`, `content`, `to`) VALUES
(1, '20', 'Menu Brush', 1),
(2, '50', 'Menu couleur sans ammoniaque, Coupe Brush', 0);

-- --------------------------------------------------------

--
-- Structure de la table `proverbe`
--

DROP TABLE IF EXISTS `proverbe`;
CREATE TABLE IF NOT EXISTS `proverbe` (
  `id` int(10) NOT NULL AUTO_INCREMENT,
  `content` varchar(300) NOT NULL,
  `auteur` varchar(100) NOT NULL,
  `date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=101 ;

--
-- Contenu de la table `proverbe`
--

INSERT INTO `proverbe` (`id`, `content`, `auteur`, `date`) VALUES
(1, 'Proin non massa non ante bibendum ullamcorper. Duis cursus, diam', 'Lydia', '2017-07-08 19:35:28'),
(2, 'eu metus. In lorem. Donec elementum, lorem ut aliquam iaculis,', 'Castor', '2017-07-08 19:35:28'),
(3, 'sit amet risus. Donec egestas. Aliquam nec enim. Nunc ut', 'Basia', '2017-07-08 19:35:28'),
(4, 'auctor. Mauris vel turpis. Aliquam adipiscing lobortis risus. In mi', 'Phyllis', '2017-07-08 19:35:28'),
(5, 'Quisque fringilla euismod enim. Etiam gravida molestie arcu. Sed eu', 'Tatum', '2017-07-08 19:35:28'),
(6, 'tellus justo sit amet nulla. Donec non justo. Proin non', 'Adrian', '2017-07-08 19:35:28'),
(7, 'nunc nulla vulputate dui, nec tempus mauris erat eget ipsum.', 'Tanek', '2017-07-08 19:35:28'),
(8, 'rhoncus id, mollis nec, cursus a, enim. Suspendisse aliquet, sem', 'Natalie', '2017-07-08 19:35:28'),
(9, 'malesuada fringilla est. Mauris eu turpis. Nulla aliquet. Proin velit.', 'Lesley', '2017-07-08 19:35:28'),
(10, 'quis, pede. Praesent eu dui. Cum sociis natoque penatibus et', 'Jennifer', '2017-07-08 19:35:28'),
(11, 'Donec est. Nunc ullamcorper, velit in aliquet lobortis, nisi nibh', 'Travis', '2017-07-08 19:35:29'),
(12, 'sem magna nec quam. Curabitur vel lectus. Cum sociis natoque', 'Lee', '2017-07-08 19:35:29'),
(13, 'est, vitae sodales nisi magna sed dui. Fusce aliquam, enim', 'Vladimir', '2017-07-08 19:35:29'),
(14, 'posuere cubilia Curae; Donec tincidunt. Donec vitae erat vel pede', 'Jackson', '2017-07-08 19:35:29'),
(15, 'Curabitur egestas nunc sed libero. Proin sed turpis nec mauris', 'Irene', '2017-07-08 19:35:29'),
(16, 'semper egestas, urna justo faucibus lectus, a sollicitudin orci sem', 'Deacon', '2017-07-08 19:35:29'),
(17, 'Nunc pulvinar arcu et pede. Nunc sed orci lobortis augue', 'Xander', '2017-07-08 19:35:29'),
(18, 'eros turpis non enim. Mauris quis turpis vitae purus gravida', 'Shay', '2017-07-08 19:35:29'),
(19, 'adipiscing lacus. Ut nec urna et arcu imperdiet ullamcorper. Duis', 'Elton', '2017-07-08 19:35:29'),
(20, 'nec, malesuada ut, sem. Nulla interdum. Curabitur dictum. Phasellus in', 'Kenneth', '2017-07-08 19:35:29'),
(21, 'interdum feugiat. Sed nec metus facilisis lorem tristique aliquet. Phasellus', 'Lani', '2017-07-08 19:35:29'),
(22, 'lorem, auctor quis, tristique ac, eleifend vitae, erat. Vivamus nisi.', 'Sade', '2017-07-08 19:35:29'),
(23, 'neque. Nullam ut nisi a odio semper cursus. Integer mollis.', 'Upton', '2017-07-08 19:35:29'),
(24, 'vehicula aliquet libero. Integer in magna. Phasellus dolor elit, pellentesque', 'Naomi', '2017-07-08 19:35:29'),
(25, 'nonummy ipsum non arcu. Vivamus sit amet risus. Donec egestas.', 'Hedda', '2017-07-08 19:35:29'),
(26, 'In lorem. Donec elementum, lorem ut aliquam iaculis, lacus pede', 'Quinn', '2017-07-08 19:35:29'),
(27, 'Maecenas iaculis aliquet diam. Sed diam lorem, auctor quis, tristique', 'Sonya', '2017-07-08 19:35:29'),
(28, 'fermentum vel, mauris. Integer sem elit, pharetra ut, pharetra sed,', 'Erich', '2017-07-08 19:35:29'),
(29, 'euismod mauris eu elit. Nulla facilisi. Sed neque. Sed eget', 'Nehru', '2017-07-08 19:35:29'),
(30, 'ac facilisis facilisis, magna tellus faucibus leo, in lobortis tellus', 'Jelani', '2017-07-08 19:35:29'),
(31, 'luctus et ultrices posuere cubilia Curae; Donec tincidunt. Donec vitae', 'Nadine', '2017-07-08 19:35:29'),
(32, 'mattis velit justo nec ante. Maecenas mi felis, adipiscing fringilla,', 'Lee', '2017-07-08 19:35:29'),
(33, 'Aliquam rutrum lorem ac risus. Morbi metus. Vivamus euismod urna.', 'Wesley', '2017-07-08 19:35:29'),
(34, 'porttitor eros nec tellus. Nunc lectus pede, ultrices a, auctor', 'Amela', '2017-07-08 19:35:29'),
(35, 'fringilla cursus purus. Nullam scelerisque neque sed sem egestas blandit.', 'Rudyard', '2017-07-08 19:35:29'),
(36, 'nec, malesuada ut, sem. Nulla interdum. Curabitur dictum. Phasellus in', 'Gay', '2017-07-08 19:35:29'),
(37, 'elit, pellentesque a, facilisis non, bibendum sed, est. Nunc laoreet', 'Stewart', '2017-07-08 19:35:29'),
(38, 'Mauris vel turpis. Aliquam adipiscing lobortis risus. In mi pede,', 'Amir', '2017-07-08 19:35:29'),
(39, 'laoreet posuere, enim nisl elementum purus, accumsan interdum libero dui', 'Jennifer', '2017-07-08 19:35:29'),
(40, 'erat eget ipsum. Suspendisse sagittis. Nullam vitae diam. Proin dolor.', 'Astra', '2017-07-08 19:35:29'),
(41, 'nunc ac mattis ornare, lectus ante dictum mi, ac mattis', 'Mason', '2017-07-08 19:35:29'),
(42, 'a, auctor non, feugiat nec, diam. Duis mi enim, condimentum', 'Alfonso', '2017-07-08 19:35:29'),
(43, 'dictum eleifend, nunc risus varius orci, in consequat enim diam', 'Leo', '2017-07-08 19:35:29'),
(44, 'aliquam adipiscing lacus. Ut nec urna et arcu imperdiet ullamcorper.', 'Jillian', '2017-07-08 19:35:29'),
(45, 'Nunc lectus pede, ultrices a, auctor non, feugiat nec, diam.', 'Hedwig', '2017-07-08 19:35:29'),
(46, 'ipsum. Suspendisse sagittis. Nullam vitae diam. Proin dolor. Nulla semper', 'Malik', '2017-07-08 19:35:29'),
(47, 'ipsum. Donec sollicitudin adipiscing ligula. Aenean gravida nunc sed pede.', 'Hayley', '2017-07-08 19:35:29'),
(48, 'commodo at, libero. Morbi accumsan laoreet ipsum. Curabitur consequat, lectus', 'Thaddeus', '2017-07-08 19:35:29'),
(49, 'eget magna. Suspendisse tristique neque venenatis lacus. Etiam bibendum fermentum', 'Rose', '2017-07-08 19:35:29'),
(50, 'tempus non, lacinia at, iaculis quis, pede. Praesent eu dui.', 'Wayne', '2017-07-08 19:35:29'),
(51, 'eu metus. In lorem. Donec elementum, lorem ut aliquam iaculis,', 'Quinn', '2017-07-08 19:35:29'),
(52, 'euismod ac, fermentum vel, mauris. Integer sem elit, pharetra ut,', 'Medge', '2017-07-08 19:35:29'),
(53, 'sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus', 'Neil', '2017-07-08 19:35:29'),
(54, 'pede. Nunc sed orci lobortis augue scelerisque mollis. Phasellus libero', 'Yoko', '2017-07-08 19:35:29'),
(55, 'senectus et netus et malesuada fames ac turpis egestas. Fusce', 'Cade', '2017-07-08 19:35:29'),
(56, 'nascetur ridiculus mus. Aenean eget magna. Suspendisse tristique neque venenatis', 'Daria', '2017-07-08 19:35:29'),
(57, 'dignissim pharetra. Nam ac nulla. In tincidunt congue turpis. In', 'Althea', '2017-07-08 19:35:29'),
(58, 'Morbi non sapien molestie orci tincidunt adipiscing. Mauris molestie pharetra', 'Jamal', '2017-07-08 19:35:29'),
(59, 'Sed nunc est, mollis non, cursus non, egestas a, dui.', 'Susan', '2017-07-08 19:35:29'),
(60, 'elementum sem, vitae aliquam eros turpis non enim. Mauris quis', 'Simone', '2017-07-08 19:35:29'),
(61, 'hendrerit. Donec porttitor tellus non magna. Nam ligula elit, pretium', 'Anastasia', '2017-07-08 19:35:29'),
(62, 'lectus ante dictum mi, ac mattis velit justo nec ante.', 'Farrah', '2017-07-08 19:35:29'),
(63, 'cursus. Integer mollis. Integer tincidunt aliquam arcu. Aliquam ultrices iaculis', 'Murphy', '2017-07-08 19:35:29'),
(64, 'Etiam ligula tortor, dictum eu, placerat eget, venenatis a, magna.', 'Quinn', '2017-07-08 19:35:29'),
(65, 'ligula. Aenean gravida nunc sed pede. Cum sociis natoque penatibus', 'Lev', '2017-07-08 19:35:29'),
(66, 'laoreet ipsum. Curabitur consequat, lectus sit amet luctus vulputate, nisi', 'Ashton', '2017-07-08 19:35:29'),
(67, 'eleifend vitae, erat. Vivamus nisi. Mauris nulla. Integer urna. Vivamus', 'Drew', '2017-07-08 19:35:29'),
(68, 'pharetra, felis eget varius ultrices, mauris ipsum porta elit, a', 'Shelly', '2017-07-08 19:35:29'),
(69, 'ipsum primis in faucibus orci luctus et ultrices posuere cubilia', 'Carlos', '2017-07-08 19:35:29'),
(70, 'lacus. Cras interdum. Nunc sollicitudin commodo ipsum. Suspendisse non leo.', 'Russell', '2017-07-08 19:35:29'),
(71, 'non, vestibulum nec, euismod in, dolor. Fusce feugiat. Lorem ipsum', 'Malcolm', '2017-07-08 19:35:29'),
(72, 'rutrum eu, ultrices sit amet, risus. Donec nibh enim, gravida', 'Ivory', '2017-07-08 19:35:29'),
(73, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices', 'Unity', '2017-07-08 19:35:29'),
(74, 'tincidunt, nunc ac mattis ornare, lectus ante dictum mi, ac', 'Uriah', '2017-07-08 19:35:29'),
(75, 'purus. Duis elementum, dui quis accumsan convallis, ante lectus convallis', 'Barrett', '2017-07-08 19:35:29'),
(76, 'at, velit. Cras lorem lorem, luctus ut, pellentesque eget, dictum', 'Ezekiel', '2017-07-08 19:35:29'),
(77, 'Nullam enim. Sed nulla ante, iaculis nec, eleifend non, dapibus', 'Stella', '2017-07-08 19:35:29'),
(78, 'mollis lectus pede et risus. Quisque libero lacus, varius et,', 'Taylor', '2017-07-08 19:35:29'),
(79, 'augue eu tellus. Phasellus elit pede, malesuada vel, venenatis vel,', 'Sylvia', '2017-07-08 19:35:29'),
(80, 'Curabitur massa. Vestibulum accumsan neque et nunc. Quisque ornare tortor', 'Ginger', '2017-07-08 19:35:29'),
(81, 'Sed eget lacus. Mauris non dui nec urna suscipit nonummy.', 'Madonna', '2017-07-08 19:35:29'),
(82, 'dui, nec tempus mauris erat eget ipsum. Suspendisse sagittis. Nullam', 'Xaviera', '2017-07-08 19:35:29'),
(83, 'tempus mauris erat eget ipsum. Suspendisse sagittis. Nullam vitae diam.', 'Teegan', '2017-07-08 19:35:29'),
(84, 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur', 'Wayne', '2017-07-08 19:35:29'),
(85, 'feugiat non, lobortis quis, pede. Suspendisse dui. Fusce diam nunc,', 'Darryl', '2017-07-08 19:35:29'),
(86, 'vel, convallis in, cursus et, eros. Proin ultrices. Duis volutpat', 'Lillith', '2017-07-08 19:35:29'),
(87, 'feugiat non, lobortis quis, pede. Suspendisse dui. Fusce diam nunc,', 'Mechelle', '2017-07-08 19:35:29'),
(88, 'sem ut cursus luctus, ipsum leo elementum sem, vitae aliquam', 'Steven', '2017-07-08 19:35:29'),
(89, 'ut, nulla. Cras eu tellus eu augue porttitor interdum. Sed', 'Urielle', '2017-07-08 19:35:29'),
(90, 'primis in faucibus orci luctus et ultrices posuere cubilia Curae;', 'Brenden', '2017-07-08 19:35:29'),
(91, 'arcu eu odio tristique pharetra. Quisque ac libero nec ligula', 'Elmo', '2017-07-08 19:35:29'),
(92, 'est. Mauris eu turpis. Nulla aliquet. Proin velit. Sed malesuada', 'Wanda', '2017-07-08 19:35:29'),
(93, 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur', 'Orson', '2017-07-08 19:35:29'),
(94, 'Maecenas ornare egestas ligula. Nullam feugiat placerat velit. Quisque varius.', 'Oscar', '2017-07-08 19:35:29'),
(95, 'tempus scelerisque, lorem ipsum sodales purus, in molestie tortor nibh', 'Boris', '2017-07-08 19:35:29'),
(96, 'id, erat. Etiam vestibulum massa rutrum magna. Cras convallis convallis', 'Renee', '2017-07-08 19:35:29'),
(97, 'lacus. Quisque purus sapien, gravida non, sollicitudin a, malesuada id,', 'Stone', '2017-07-08 19:35:29'),
(98, 'hendrerit. Donec porttitor tellus non magna. Nam ligula elit, pretium', 'Rana', '2017-07-08 19:35:29'),
(99, 'mus. Donec dignissim magna a tortor. Nunc commodo auctor velit.', 'Zeus', '2017-07-08 19:35:29'),
(100, 'elit, pharetra ut, pharetra sed, hendrerit a, arcu. Sed et', 'Lesley', '2017-07-08 19:35:29');

-- --------------------------------------------------------

--
-- Structure de la table `user`
--

DROP TABLE IF EXISTS `user`;
CREATE TABLE IF NOT EXISTS `user` (
  `id` int(10) NOT NULL AUTO_INCREMENT,
  `identifiant` varchar(255) NOT NULL,
  `mdp` varchar(32) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=2 ;

--
-- Contenu de la table `user`
--

INSERT INTO `user` (`id`, `identifiant`, `mdp`) VALUES
(1, 'admin', 'hairessentiel');

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
